name: kalshi_tha
description: "Take Home Assignment"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  mocktail: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-Light.ttf
          weight: 100
        - asset: fonts/rubik/Rubik-Medium.ttf
          weight: 400
        - asset: fonts/rubik/Rubik-Regular.ttf
          weight: 500
        - asset: fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/rubik/Rubik-Black.ttf
          weight: 800

    - family: WorkSans
      fonts:
        - asset: fonts/work_sans/WorkSans-Thin.ttf
          weight: 100
        - asset: fonts/work_sans/WorkSans-Light.ttf
          weight: 300
        - asset: fonts/work_sans/WorkSans-Medium.ttf
          weight: 400
        - asset: fonts/work_sans/WorkSans-Regular.ttf
          weight: 500
        - asset: fonts/work_sans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: fonts/work_sans/WorkSans-Bold.ttf
          weight: 700
        - asset: fonts/work_sans/WorkSans-Black.ttf
          weight: 800
